#importando a biblioteca pyautogui
import pyautogui as py
import time as t
t.sleep(0.5)
py.press('winleft')
t.sleep(0.5)
py.write('edge')
t.sleep(0.5)
py.press('enter')
t.sleep(0.5)
py.write('https://www.youtube.com.br',interval=0.05)
t.sleep(0.5)
py.press('enter')
t.sleep(3.0)
py.click(432,134)
t.sleep(0.5)
py.write('palmeiras x corinthians', interval=0.05)
t.sleep(0.5)
py.press('enter')
t.sleep(0.5)
py.moveTo(1584,139)
t.sleep(0.5)
py.click()
t.sleep(0.5)
py.scroll(-1300)
t.sleep(0.5)
py.click(297,365)
t.sleep(20)
py.hotkey('alt','F4')
py.alert('Fim do Script')